I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/extremis/coteries/templiers/evts_UnivTempliers.rpy", line 142, in script
    $ situation_.AjouterACarac(metier.TueurDeMonstre.NOM, 1)
  File "game/extremis/coteries/templiers/evts_UnivTempliers.rpy", line 142, in <module>
    $ situation_.AjouterACarac(metier.TueurDeMonstre.NOM, 1)
AttributeError: 'module' object has no attribute 'TueurDeMonstre'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/extremis/coteries/templiers/evts_UnivTempliers.rpy", line 142, in script
    $ situation_.AjouterACarac(metier.TueurDeMonstre.NOM, 1)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/extremis/coteries/templiers/evts_UnivTempliers.rpy", line 142, in <module>
    $ situation_.AjouterACarac(metier.TueurDeMonstre.NOM, 1)
AttributeError: 'module' object has no attribute 'TueurDeMonstre'

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DestinExtremis 1.0
Tue Feb 02 20:59:14 2021
