I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
IOError: [Errno 13] Permission denied: 'D:\\boulot\\RenPy\\destinRenpy\\game\\saves\\navigation.json.new'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\main.py", line 534, in main
    renpy.dump.dump(False)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\dump.py", line 249, in dump
    with file(new, "w") as f:
IOError: [Errno 13] Permission denied: 'D:\\boulot\\RenPy\\destinRenpy\\game\\saves\\navigation.json.new'

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DestinExtremis 1.0
Thu Feb 18 20:33:58 2021
